parameters:
    app.feeds:
        - https://www.archlinux.de/news/feed
        - http://5in4.de/blog/category/arch-linux/feed/atom/
        - https://trompetenkaefer.wordpress.com/tag/archlinux/feed/atom/
        - https://yhaupenthal.org/linux.xml
        - https://blog.stefan-betz.net/tags/arch/index.xml
        - https://www.loggn.de/tag/planet-archlinux-de/feed/atom/
        - https://edermi.github.io/post/index.xml
